version: '3'
services:
  service_container_project:
    build:
      context: ../
      dockerfile: ./docker/docker_cuda_11/Dockerfile
    container_name: project_container
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
    command: ["bash"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - ../:/home/user/code

  
